"""empty message

Revision ID: 1b7b4aafc236
Revises: 
Create Date: 2019-11-26 09:23:53.514308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7b4aafc236'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_name', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id_name'), 'subject', ['id_name'], unique=True)
    op.create_index(op.f('ix_subject_path'), 'subject', ['path'], unique=True)
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id_name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['subject_id_name'], ['subject.id_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_timestamp'), 'update', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_timestamp'), table_name='update')
    op.drop_table('update')
    op.drop_index(op.f('ix_subject_path'), table_name='subject')
    op.drop_index(op.f('ix_subject_id_name'), table_name='subject')
    op.drop_table('subject')
    # ### end Alembic commands ###
